name: datagenius-pro
channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.11
  
  # Core Data Science
  - pandas=2.2.0
  - numpy=1.26.3
  - scikit-learn=1.4.0
  
  # Visualization
  - matplotlib=3.8.2
  - seaborn=0.13.1
  - plotly=5.18.0
  
  # Jupyter (for notebooks)
  - jupyter=1.0.0
  - ipykernel=6.29.0
  
  # Database
  - postgresql=16.1
  - redis=7.2.4
  
  # System tools
  - git=2.43.0
  - make=4.3
  
  # Pip packages
  - pip=23.3.2
  - pip:
    - streamlit==1.31.0
    - streamlit-extras==0.3.6
    - pycaret==3.2.0
    - xgboost==2.0.3
    - lightgbm==4.3.0
    - catboost==1.2.2
    - shap==0.44.1
    - lime==0.2.0.1
    - anthropic==0.18.1
    - openai==1.12.0
    - langchain==0.1.6
    - sqlalchemy==2.0.25
    - alembic==1.13.1
    - pydantic==2.6.0
    - pydantic-settings==2.1.0
    - python-dotenv==1.0.1
    - mlflow==2.10.2
    - evidently==0.4.13
    - reportlab==4.0.9
    - fastapi==0.109.0
    - uvicorn==0.27.0
    - pytest==8.0.0
    - pytest-cov==4.1.0
    - loguru==0.7.2
    - tqdm==4.66.1
    - joblib==1.3.2
    - polars==0.20.6
    - great-expectations==0.18.8
    - prometheus-client==0.19.0
    - apscheduler==3.10.4
    - alibi-detect==0.11.4